#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>

void print_usage(char* progname) {
	fprintf(stderr, "Usage:\n");
	fprintf(stderr, "  %s inputfile [outputfile [varname]]\n", progname);
}

unsigned char* read_data_from_file(char* fname, size_t* bufsize) {
	FILE* fp = fopen(fname, "rb");
	if (!fp)
		return NULL;

	fseek(fp, 0, SEEK_END);
	*bufsize = ftell(fp);
	fseek(fp, 0, SEEK_SET);

	unsigned char* buffer = malloc(*bufsize);
	fread(buffer, 1, *bufsize, fp);

	fclose(fp);
	return buffer;
}


int main(int argc, char* argv[]) {
	// process arguments
	if (argc < 2) {
		print_usage(argv[0]);
		return 1;
	}

	char* infname = argv[1];
	char* outfname = (argc > 2 ? argv[2] : NULL);
	char* varname = (argc > 3 ? argv[3] : "bin");

	size_t bufsize;
	unsigned char* inbuf = read_data_from_file(infname, &bufsize);
	if (!inbuf) {
		fprintf(stderr, "Error opening file %s\n", infname);
		return 2;
	}

	FILE* fpout = stdout;
	if (outfname != NULL) {
		fpout = fopen(outfname, "w");
		if (!fpout) {
			fprintf(stderr, "Error opening output file %s\n", outfname);
			return 3;
		}
	}

	fprintf(fpout, "/* Generated by bin2c from %s */\n", infname);
	fprintf(fpout, "#include <stddef.h>\n\n");
	fprintf(fpout, "const unsigned char %s[%zu] = {\n\t", varname, bufsize);
	
	size_t count = 0;
	for (size_t ii = 0; ii < bufsize - 1; ++ii) {
		fprintf(fpout, "0x%02x,", inbuf[ii]);
		++count;
		if (count == 16) {
			fprintf(fpout, "\n\t");
			count = 0;
		}
	}
	// last byte
	fprintf(fpout, "0x%02x\n", inbuf[bufsize - 1]);
	fprintf(fpout, "};\n");
	fprintf(fpout, "const size_t %s_size = %zu;\n", varname, bufsize);
	
	if (fpout != stdout)
		fclose(fpout);
	free(inbuf); // no need, OS will do it anyway, but okay
	return 0;
}
